github.com:
    users:
        C00zzy:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: C00zzy
